services:
  speech-emotion-app:
    image: 2000030906/speech-emotion-app:latest
    command: sh -c "pip install flask-sqlalchemy && gunicorn --workers=2 --timeout=300 --bind=0.0.0.0:50005 app:app"
    container_name: speech-emotion-app
    ports:
      - "50005:50005"
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
    volumes:
      - .:/app
    restart: unless-stopped
