[project]
name = "capstone-project-1"
version = "0.1.0"
description = "Speech Emotion Recognition App"
requires-python = "==3.12.*"
dependencies = [
    "flask",
    "numpy>=1.26.0",
    "librosa",
    "scikit-learn==1.3.0",
    "pandas",
    "seaborn",
    "matplotlib",
    "tqdm",
    "joblib",
    "moviepy>=1.0.3",
    "imageio-ffmpeg",
    "pydub",
    "gunicorn",
    "soxr>=0.3.0",
    "resampy",
    "tensorflow-cpu>=2.16.0",
    "opencv-python-headless",
    "fer>=22.5.1",
    "flask-sqlalchemy"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
